steps:
# Step 1
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: [
   '-c',
   'docker pull gcr.io/airy-advantage-336608/coffe-app:1.1 || exit 0'
  ]
# Step 2
- name: gcr.io/cloud-builders/docker
  args: [
   'build',
   '-t',
   'gcr.io/airy-advantage-336608/coffe-app:1.1',
   '.'
  ]
  dir: 'coffe-app'
# Step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=coffe-cluster'
# Step 4
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set',
   'image',
   'deployment',
   'coffe-app',
   'coffe-app=gcr.io/airy-advantage-336608/coffe-app:1.1'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=coffe-cluster'
  # Push the image to Google Container Registry with the 1.1 tag
images: [
   'gcr.io/airy-advantage-336608/coffe-app:1.1'
  ]
